title: Mapeamento
description: Mapeamento sistemático de referências bibliográficas
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

# aux_links:
#  Template Repository: https://wmpjrufg.github.io/EASYPLOTPY/

# Back to top link
back_to_top: true
back_to_top_text: "Voltar ao topo"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Novo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false